import Head from 'next/head';
import Header from '@/components/header/header';
import Hero from '@/components/index/hero';
import About from '@/components/index/about';
import Services from '@/components/index/services';
import Memberships from '@/components/index/memberships';
import Reviews from '@/components/index/reviews';
import Contact from '@/components/index/contact';
import Footer from '@/components/footer/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>x365</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/kharkiv-tone.ttf" as="font" type="font/ttf" crossOrigin="anonymous" />
        <link rel="preload" href="/mulish-regular.ttf" as="font" type="font/ttf" crossOrigin="anonymous" />
        <link rel="preload" href="/mulish-semi-bold.ttf" as="font" type="font/ttf" crossOrigin="anonymous" />
      </Head>
      
      <Header />
      <Hero />
      <About/>
      <Services/>
      <Memberships/>
      <Reviews/>
      <Contact/>
      <Footer/>
    </>
  );
}
